package cli

import (
	"github.com/ferricstore/command-line/internal/connection"
	ferricstore "github.com/ferricstore/ferricstore-go"
)

// These assertions make the command tree's OSS SDK contract compile-time
// checked. Runtime capability checks remain useful for deliberately partial or
// mocked Enterprise providers, but the official client must support every
// command advertised by this build.
var (
	_ connection.Client        = (*ferricstore.Client)(nil)
	_ pingClient               = (*ferricstore.Client)(nil)
	_ sdkCommander             = (*ferricstore.Client)(nil)
	_ transactionStarter       = (*ferricstore.Client)(nil)
	_ aclOperator              = (*ferricstore.Client)(nil)
	_ namespaceUsageReader     = (*ferricstore.Client)(nil)
	_ quotaUsageReader         = (*ferricstore.Client)(nil)
	_ clusterHealthReader      = (*ferricstore.Client)(nil)
	_ clusterStatsReader       = (*ferricstore.Client)(nil)
	_ clusterStatusReader      = (*ferricstore.Client)(nil)
	_ clusterRoleReader        = (*ferricstore.Client)(nil)
	_ clusterKeySlotReader     = (*ferricstore.Client)(nil)
	_ clusterSlotsReader       = (*ferricstore.Client)(nil)
	_ clusterJoiner            = (*ferricstore.Client)(nil)
	_ clusterLeaver            = (*ferricstore.Client)(nil)
	_ clusterFailoverOperator  = (*ferricstore.Client)(nil)
	_ clusterPromoter          = (*ferricstore.Client)(nil)
	_ clusterDemoter           = (*ferricstore.Client)(nil)
	_ flowEnqueuer             = (*ferricstore.Client)(nil)
	_ flowJobClaimer           = (*ferricstore.Client)(nil)
	_ flowGetter               = (*ferricstore.Client)(nil)
	_ flowLister               = (*ferricstore.Client)(nil)
	_ flowLeaseExtender        = (*ferricstore.Client)(nil)
	_ flowCompleter            = (*ferricstore.Client)(nil)
	_ flowRetrier              = (*ferricstore.Client)(nil)
	_ flowFailer               = (*ferricstore.Client)(nil)
	_ flowCanceller            = (*ferricstore.Client)(nil)
	_ flowHistorian            = (*ferricstore.Client)(nil)
	_ flowStatsReader          = (*ferricstore.Client)(nil)
	_ flowPolicyGetter         = (*ferricstore.Client)(nil)
	_ flowPolicySetter         = (*ferricstore.Client)(nil)
	_ flowCreator              = (*ferricstore.Client)(nil)
	_ flowClaimer              = (*ferricstore.Client)(nil)
	_ flowSearcher             = (*ferricstore.Client)(nil)
	_ flowSignaler             = (*ferricstore.Client)(nil)
	_ flowTransitioner         = (*ferricstore.Client)(nil)
	_ flowRewinder             = (*ferricstore.Client)(nil)
	_ flowByParentReader       = (*ferricstore.Client)(nil)
	_ flowByRootReader         = (*ferricstore.Client)(nil)
	_ flowByCorrelationReader  = (*ferricstore.Client)(nil)
	_ flowTerminalsReader      = (*ferricstore.Client)(nil)
	_ flowFailuresReader       = (*ferricstore.Client)(nil)
	_ flowStuckReader          = (*ferricstore.Client)(nil)
	_ flowInfoReader           = (*ferricstore.Client)(nil)
	_ flowValueReader          = (*ferricstore.Client)(nil)
	_ flowQuerier              = (*ferricstore.Client)(nil)
	_ flowExplainer            = (*ferricstore.Client)(nil)
	_ flowQueryIndexReader     = (*ferricstore.Client)(nil)
	_ scheduleCreator          = (*ferricstore.Client)(nil)
	_ scheduleGetter           = (*ferricstore.Client)(nil)
	_ scheduleLister           = (*ferricstore.Client)(nil)
	_ schedulePauser           = (*ferricstore.Client)(nil)
	_ scheduleResumer          = (*ferricstore.Client)(nil)
	_ scheduleTriggerer        = (*ferricstore.Client)(nil)
	_ scheduleDueFirer         = (*ferricstore.Client)(nil)
	_ scheduleDeleter          = (*ferricstore.Client)(nil)
	_ governanceOverviewReader = (*ferricstore.Client)(nil)
	_ approvalRequester        = (*ferricstore.Client)(nil)
	_ approvalGetter           = (*ferricstore.Client)(nil)
	_ approvalLister           = (*ferricstore.Client)(nil)
	_ approvalApprover         = (*ferricstore.Client)(nil)
	_ approvalRejecter         = (*ferricstore.Client)(nil)
	_ circuitGetter            = (*ferricstore.Client)(nil)
	_ circuitOpener            = (*ferricstore.Client)(nil)
	_ circuitCloser            = (*ferricstore.Client)(nil)
	_ budgetGetter             = (*ferricstore.Client)(nil)
	_ budgetLister             = (*ferricstore.Client)(nil)
	_ budgetReserver           = (*ferricstore.Client)(nil)
	_ budgetCommitter          = (*ferricstore.Client)(nil)
	_ budgetReleaser           = (*ferricstore.Client)(nil)
	_ limitGetter              = (*ferricstore.Client)(nil)
	_ limitLister              = (*ferricstore.Client)(nil)
	_ limitLeaser              = (*ferricstore.Client)(nil)
	_ limitSpender             = (*ferricstore.Client)(nil)
	_ limitReleaser            = (*ferricstore.Client)(nil)
	_ effectGetter             = (*ferricstore.Client)(nil)
	_ effectReserver           = (*ferricstore.Client)(nil)
	_ effectConfirmer          = (*ferricstore.Client)(nil)
	_ effectFailer             = (*ferricstore.Client)(nil)
	_ effectCompensator        = (*ferricstore.Client)(nil)
)
